version: '3'
services:
  app:
    container_name: docker-node-mongo4
    restart: always
    build: .
    ports: 
      - '8887:8887'
    links:
      - mongo4
  mongo4:
    container_name: mongo4
    image: mongo
    ports:
      - '127.0.0.1:27018:27017'
