version: '3'
services:
  app:
    container_name: docker-node-mongo2
    restart: always
    build: .
    ports: 
      - '8887:8887'
    links:
      - mongo2
  mongo2:
    container_name: mongo2
    image: mongo
    ports:
      - '127.0.0.1:27018:27017'
